Add reviews
Leibnitz80/java-filmorate pull request #16
Opened 2023-03-30 20:27 UTC by evgeniyvlee

2023-03-31 18:47 UTC, SergeiBrin requested changes
Не претендую на истину. Могу ошибаться. Жду Фидбек 😺

2023-03-31 18:47 UTC, SergeiBrin commented on src/main/java/ru/yandex/practicum/filmorate/model/Review.java
> +    }
Такое ощущение, что конструктор не используется.  А если используется, то может его удалить и дописать для класса аннотацию @NoArgsConstructor

2023-03-31 18:47 UTC, SergeiBrin commented on src/main/java/ru/yandex/practicum/filmorate/model/Review.java
> +    @JsonIgnore
Может сделать final?

2023-03-31 18:47 UTC, SergeiBrin commented on src/main/java/ru/yandex/practicum/filmorate/dao/ReviewDbStorage.java
> +        Review review = jdbcTemplate.queryForObject(getReviewByIdSql, (rs, rowNum) -> makeReview(rs), id);
Можеть быть тут сразу же сделать return?
``` java
return jdbcTemplate.queryForObject(getReviewByIdSql, (rs, rowNum) -> makeReview(rs), id);
```

2023-03-31 18:51 UTC, SergeiBrin commented on src/main/java/ru/yandex/practicum/filmorate/model/Review.java
> +    private Set<Long> likes = new HashSet<>();
Может сделать final?

2023-03-31 18:52 UTC, SergeiBrin commented on src/main/java/ru/yandex/practicum/filmorate/model/Review.java
> +    private Set<Long> dislikes = new HashSet<>();
Может сделать final?

2023-03-31 18:53 UTC, SergeiBrin commented on src/main/java/ru/yandex/practicum/filmorate/dao/ReviewDbStorage.java
> +    }
Можеть быть тут сразу же сделать return?
``` java
return jdbcTemplate.queryForObject(getReviewByIdSql, (rs, rowNum) -> makeReview(rs), id);
```

2023-03-31 18:55 UTC, SergeiBrin commented on src/main/java/ru/yandex/practicum/filmorate/model/Review.java
> +
Такое ощущение, что конструктор не используется.  А если используется, то может его удалить и дописать для класса аннотацию @NoArgsConstructor?

2023-03-31 19:19 UTC, Elina1313 commented on src/main/java/ru/yandex/practicum/filmorate/controller/ReviewController.java
> +    @Autowired
Конструктор можно заменять аннотацией над классом `@RequiredArgsConstructor`

2023-03-31 19:19 UTC, Elina1313 commented on src/main/java/ru/yandex/practicum/filmorate/controller/ReviewController.java
> +        log.info("Запрос: GET by id");
логи пишем вроде для разработчиков, т.е лучше думаю использовать log.debug(), и прописывать в каждом контроллере что за тип запроса был вызван(GET, POST итд) тоже не особо практично) log.debug будет выводить эту информацию сам

2023-03-31 19:19 UTC, Elina1313 commented on src/main/java/ru/yandex/practicum/filmorate/service/ReviewService.java
> +    @Autowired
тут аналогично `@RequiredArgsConstructor`

2023-03-31 19:19 UTC, Elina1313 commented on src/main/java/ru/yandex/practicum/filmorate/service/ReviewService.java
> +    }
в этих двух методах можно не указывать тип возврата, достаточно например `List  getReviews()`

2023-03-31 19:19 UTC, Elina1313 commented on src/main/java/ru/yandex/practicum/filmorate/dao/ReviewDbStorage.java
> +
keyHolder это круто, но есть способ чуть проще, можно вот так

 SimpleJdbcInsert simpleJdbcInsert = new SimpleJdbcInsert(jdbcTemplate)
                .withTableName("Reviews")
                .usingGeneratedKeyColumns("review_id");


       MapSqlParameterSource params = new MapSqlParameterSource()
                .addValue("content", review.getContent())
                .addValue("isPositive", review.getIsPositive())
                .addValue("user_id", review.getUserId())
                .addValue("film_id", review.getFilmId())
                .addValue("useful", review.getUseful());

        Long id = simpleJdbcInsert.executeAndReturnKey(params).longValue();
        review.setReviewId(id);

        return getReviewById(review.getReviewId());

2023-03-31 19:19 UTC, Elina1313 commented on src/main/java/ru/yandex/practicum/filmorate/dao/ReviewDbStorage.java
> +                    String.format("Отзыв c id= %d не найден!", id));
тут можно немного покороче и лаконичнее
String sql = "select count(1) as row_count from Reviews where review_id = ?;";
        Optional.ofNullable(jdbcTemplate.queryForObject(sql, (rs, rowNum) -> rs.getLong("row_count"), id))
                .filter(x -> x > 0)
                .orElseThrow(() -> new NotFoundException(String.format("Отзыв c id= %d не найден!", id)));

2023-03-31 19:22 UTC, Elina1313 commented on src/main/java/ru/yandex/practicum/filmorate/dao/ReviewDbStorage.java
> +
если добавлять такую конструкцию, то в модели Review нужна аннотация, чтоб null не проходил
 @NotNull
    private Boolean isPositive;

2023-03-31 19:23 UTC, Elina1313 approved these changes

2023-03-31 19:43 UTC, Leibnitz80 requested changes

2023-03-31 19:43 UTC, Leibnitz80 commented on src/main/java/ru/yandex/practicum/filmorate/dao/ReviewDbStorage.java
> +                .likes(new HashSet<>())
У тебя же внутри класса лайки и дислайки уже инициализируются при создании объекта. Зачем здесь их ещё раз создавать?

2023-03-31 20:29 UTC, SergeiBrin commented on src/main/java/ru/yandex/practicum/filmorate/dao/ReviewDbStorage.java
> +                    String.format("Отзыв c id= %d не найден!", id));
Если код d комменте завернуть в такую конструкцию

''' java
Здесь код
'''

то будет поприкольней)))

2023-03-31 20:49 UTC, Elina1313 commented on src/main/java/ru/yandex/practicum/filmorate/dao/ReviewDbStorage.java
> +                    String.format("Отзыв c id= %d не найден!", id));
да, только ``` , а такие не работают ''' )

2023-04-01 19:02 UTC, SergeiBrin approved these changes

2023-04-01 20:58 UTC, Leibnitz80 approved these changes

2023-04-01 20:59 UTC, merged