add-most-populars
Leibnitz80/java-filmorate pull request #22
Opened 2023-04-02 11:26 UTC by sevvmish

Вывод самых популярных фильмов по жанру и годам

2023-04-02 13:42 UTC, Leibnitz80 commented
Решили перенести логику отбора на сторону СУБД

2023-04-02 13:44 UTC, Leibnitz80 requested changes

2023-04-02 13:44 UTC, Leibnitz80 commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    public List<Film> getTopFilms(Integer count, Integer genreId, Integer year) {
Решили перенести логику отбора данных на сторону СУБД

2023-04-02 17:12 UTC, sevvmish commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    public List<Film> getTopFilms(Integer count, Integer genreId, Integer year) {
всё верно, исправил

2023-04-02 20:14 UTC, Leibnitz80 requested changes

2023-04-02 20:14 UTC, Leibnitz80 commented on src/main/java/ru/yandex/practicum/filmorate/dao/FilmDbStorage.java
> +        String genreConditionOnly = " LEFT JOIN Genres_Relation ON films.film_id = Genres_Relation.film_id" +
Думаю тут Inner больше подойдёт

2023-04-02 20:33 UTC, sevvmish commented on src/main/java/ru/yandex/practicum/filmorate/dao/FilmDbStorage.java
> +        String genreConditionOnly = " LEFT JOIN Genres_Relation ON films.film_id = Genres_Relation.film_id" +
ОК, исправил

2023-04-02 20:51 UTC, Leibnitz80 approved these changes

2023-04-02 23:26 UTC, SergeiBrin approved these changes, later dismissed
Костя, если ты с чем-то не согласен, то оязательно напиши. Я считаю, что можно сделать проще, но если ты не согласен, то я сделаю Approve.

2023-04-02 23:26 UTC, SergeiTakt commented on src/main/java/ru/yandex/practicum/filmorate/dao/FilmDbStorage.java
> +        return filmsMap.values().stream().collect(Collectors.toList());
Можно проще ```return new ArrayList<>(filmsMap.values());```

2023-04-02 23:26 UTC, SergeiTakt commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +                            @RequestParam(required = false, name = "year") @Nullable Integer year) {
Есть ощущение, что ```required = false``` изначально предполагает, что если значение не будет передано, то будет Null. Нужен ли тогда ```@Nullable```?

2023-04-02 23:26 UTC, SergeiBrin commented on src/main/java/ru/yandex/practicum/filmorate/dao/FilmDbStorage.java
> +    }
Почему не так?
 ```jdbcTemplate.query();``` не выбрасывает ошибку и возвращает пустой лист, если ничего не нашел, да и в тестах Postman нет такого теста, где в popular films возращается ошибка - там либо данные, либо пустой лист. Плюс не нужно будет писать лишние методы - ведь в классе уже есть все необходимое для обработки подобного запроса.
 
``` Java
 @Override
    public List<Film> getTopFilms(Integer count, Integer genreId, Integer year) {
        String currentCondition = "";

        String yearConditionOnly = " WHERE YEAR(f.releaseDate) = " + year + " ";

        String genreConditionOnly = " INNER JOIN Genres_Relation gr ON f.film_id = gr.film_id" +
                                    " WHERE gr.GENRE_ID = " + genreId + " ";

        String yearAndGenreConditions = " INNER JOIN Genres_Relation gr ON f.film_id = gr.film_id" +
                                        " WHERE gr.GENRE_ID = " + genreId + " AND YEAR(f.releaseDate) = " + year + " ";

        if (genreId != null && year == null) {
            currentCondition = genreConditionOnly;
        } else if (genreId == null && year != null) {
            currentCondition = yearConditionOnly;
        } else if (genreId != null && year != null) {
            currentCondition = yearAndGenreConditions;
        }


        String sql = "select f.film_id, f.name, f.description, f.releaseDate, f.duration, r.mpa_id, r.name as mpa_name " +
                     "from Films f " +
                     "join Mpa as r on f.mpa_id = r.mpa_id " +
                     "left join Likes as l on f.film_id = l.film_id " + currentCondition +
                     "group by f.film_id " +
                     "order by count(l.user_id) DESC " +
                     "limit ?";


        List<Film> films = jdbcTemplate.query(sql, (rs, rowNum) -> makeFilm(rs), count);

        sql = "select distinct gr.film_id, g.genre_id, g.name " +
                "from Genres_Relation gr " +
                "inner join Genres g on g.genre_id = gr.genre_id " +
                "order by g.genre_id";

        jdbcTemplate.query(sql, (rx, rowNum) -> parseGenres(rx, films));
        getDirectorsIntoFilms(films);

        return films;
    }
```

2023-04-02 23:37 UTC, SergeiBrin commented on src/main/java/ru/yandex/practicum/filmorate/dao/FilmDbStorage.java
> +    public List<Film> getTopFilms(Integer count, Integer genreId, Integer year) {
Почему не так?
 ```jdbcTemplate.query();``` не выбрасывает ошибку и возвращает пустой лист, если ничего не нашел, да и в тестах Postman нет такого теста, где в popular films возращается ошибка - там либо данные, либо пустой лист. Плюс не нужно будет писать лишние методы - ведь в классе уже есть все необходимое для обработки подобного запроса.
 
``` Java
 @Override
    public List<Film> getTopFilms(Integer count, Integer genreId, Integer year) {
        String currentCondition = "";

        String yearConditionOnly = " WHERE YEAR(f.releaseDate) = " + year + " ";

        String genreConditionOnly = " INNER JOIN Genres_Relation gr ON f.film_id = gr.film_id" +
                                    " WHERE gr.GENRE_ID = " + genreId + " ";

        String yearAndGenreConditions = " INNER JOIN Genres_Relation gr ON f.film_id = gr.film_id" +
                                        " WHERE gr.GENRE_ID = " + genreId + " AND YEAR(f.releaseDate) = " + year + " ";

        if (genreId != null && year == null) {
            currentCondition = genreConditionOnly;
        } else if (genreId == null && year != null) {
            currentCondition = yearConditionOnly;
        } else if (genreId != null && year != null) {
            currentCondition = yearAndGenreConditions;
        }


        String sql = "select f.film_id, f.name, f.description, f.releaseDate, f.duration, r.mpa_id, r.name as mpa_name " +
                     "from Films f " +
                     "join Mpa as r on f.mpa_id = r.mpa_id " +
                     "left join Likes as l on f.film_id = l.film_id " + currentCondition +
                     "group by f.film_id " +
                     "order by count(l.user_id) DESC " +
                     "limit ?";


        List<Film> films = jdbcTemplate.query(sql, (rs, rowNum) -> makeFilm(rs), count);

        sql = "select distinct gr.film_id, g.genre_id, g.name " +
                "from Genres_Relation gr " +
                "inner join Genres g on g.genre_id = gr.genre_id " +
                "order by g.genre_id";

        jdbcTemplate.query(sql, (rx, rowNum) -> parseGenres(rx, films));
        getDirectorsIntoFilms(films);

        return films;
    }
```

2023-04-03 06:47 UTC, sevvmish commented on src/main/java/ru/yandex/practicum/filmorate/dao/FilmDbStorage.java
> +    public List<Film> getTopFilms(Integer count, Integer genreId, Integer year) {
тут не требуется в обязательном порядке try catch =)) я его больше для проверки правильности работы оставлял. В принципе, наличие try catch не возбраняется ревьверами при проверке потом. В ином случае - можно просто удалить.

Почему я использовал свой вариант, а не приведенный пример. В данном примере мы возвращаемся к проблеме, с которой начали (первое ревью этой ветки): сначала берем из БД весь кусок всех жанров и фильмов к ним, какие есть в БД (а уже потом получаем из них нужные):

"select distinct gr.film_id, g.genre_id, g.name " +
                "from Genres_Relation gr " +
                "inner join Genres g on g.genre_id = gr.genre_id " +
                "order by g.genre_id";

Но это не эффективно. Пока в базе пару фильмов, все ОК (в плане: производительность не пострадает), а когда их станет 100500, то делать запрос на получение 100500 * х(сколько жанров в фильме) и потом обрабатывать такой огромный кусок ради получения списка из 10... ну может 20 фильмов ТОПа - не правильно.

В моем варианте queryForRowSet, помимо своей работы, формирует мапу, которая в будущем запрашивает конкретный список филмИД и получает только те жанры, которые нужны для этих филмИД.

2023-04-03 06:51 UTC, sevvmish commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +                            @RequestParam(required = false, name = "year") @Nullable Integer year) {
да, тесты ошибок не показали, могу убрать.

2023-04-03 06:55 UTC, sevvmish commented on src/main/java/ru/yandex/practicum/filmorate/dao/FilmDbStorage.java
> +        return filmsMap.values().stream().collect(Collectors.toList());
да, можно так.

2023-04-03 07:01 UTC, SergeiBrin commented on src/main/java/ru/yandex/practicum/filmorate/dao/FilmDbStorage.java
> +    public List<Film> getTopFilms(Integer count, Integer genreId, Integer year) {
Очень круто ))))

2023-04-03 07:05 UTC, SergeiBrin approved these changes

2023-04-03 08:12 UTC, SergeiBrin approved these changes

2023-04-03 16:01 UTC, Leibnitz80 approved these changes

2023-04-03 16:02 UTC, merged