Add remove user or film from database
Leibnitz80/java-filmorate pull request #9
Opened 2023-03-29 10:24 UTC by SergeiBrin

2023-03-29 17:10 UTC, sevvmish commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        userStorage.checkUserContains(id);
Этот вызов проверки можно упростить. Тем более, что он дублирует другой такой же метод, еще одну проверку, уже в классе UserDbStorage в методе deleteUser(Long id). 
Если я не ошибаюсь, постман не выдает ошибку, если мы пытаемся удалить не существующего юзера без возврата 404.

2023-03-29 19:58 UTC, Leibnitz80 requested changes

2023-03-29 19:58 UTC, Leibnitz80 commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        if (film.getMpa().getId() < 1 || film.getMpa().getId() > 5) {
Жанры и категории впоследствии могут добавиться новые. Лучше не ограничиваться N штуками

2023-03-29 19:58 UTC, Leibnitz80 commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryUserStorage.java
> +        User user2 = getUserById(userId); // Здесь было friendId
Убери этот комментарий. На ревью видно что было, что стало

2023-03-29 20:07 UTC, sevvmish requested changes
есть что исправить

2023-03-30 10:44 UTC, SergeiBrin commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        if (film.getMpa().getId() < 1 || film.getMpa().getId() > 5) {
Если не ограничить, то в таблицу можно положить несуществующий mpa_id, например -250

2023-03-30 10:45 UTC, SergeiBrin commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        userStorage.checkUserContains(id);
👍

2023-03-30 10:50 UTC, SergeiBrin commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        userStorage.checkUserContains(id);
Постману нужен возврат 404, когда он хочет получить список друзей несуществующего юзера.

2023-03-30 10:51 UTC, SergeiBrin commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        if (film.getMpa().getId() < 1 || film.getMpa().getId() > 5) {
Как быть?

2023-03-30 10:53 UTC, SergeiBrin commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryUserStorage.java
> +        User user2 = getUserById(userId); // Здесь было friendId
🆗

2023-03-30 10:57 UTC, SergeiBrin commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        userStorage.checkUserContains(id);
А тут я просто скопипастил, чтоб было как у Димы.

2023-03-30 10:59 UTC, SergeiBrin commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        userStorage.checkUserContains(id);
Хотя нет, посмотрел, и это не копипаст, извиняюсь.

2023-03-30 11:04 UTC, SergeiBrin commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        userStorage.checkUserContains(id);
Да, это лишняя проверка при удалении пользовавтеля, потому что она уже есть у Димы в стораджах. Признаю ошибку на все 100 :)

2023-03-30 11:19 UTC, SergeiBrin commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        userStorage.checkUserContains(id);
✅

2023-03-30 11:20 UTC, SergeiBrin commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryUserStorage.java
> +        User user2 = getUserById(userId); // Здесь было friendId
✅

2023-03-30 13:03 UTC, SergeiBrin commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        if (film.getMpa().getId() < 1 || film.getMpa().getId() > 5) {
✅

2023-03-30 13:05 UTC, SergeiBrin commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        if (film.getMpa().getId() < 1 || film.getMpa().getId() > 5) {
✅

2023-03-30 13:06 UTC, sevvmish approved these changes
Все ок.

2023-03-30 13:08 UTC, SergeiBrin commented
Замечания устранил. Develop обновил, конфликты со своей веткой устранил. И чуть поправил стайл sql запросов, чтобы смотрелось эстетично 😸

2023-03-30 15:15 UTC, evgeniyvlee reviewed
Все ок. Замечаний нет)

2023-03-30 17:30 UTC, Leibnitz80 approved these changes

2023-03-30 17:32 UTC, merged